# -*- coding: utf-8 -*-
"""Streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZHv114PEbfwxPSEaxeX_lNF43t3t7my
"""

pip install PyPDF2

"""To upload unknown file"""

pip install streamlit

import PyPDF2
import io
import re
import streamlit as st
from google.colab import files

st.title("AI Resume Scanner")
st.write("Upload your resume to get a score and suggestions.")

uploaded_file = st.file_uploader("Choose your resume (PDF)", type=["pdf"])

if uploaded_file:

    pdf_file = io.BytesIO(uploaded_file.getvalue())
    filereader = PyPDF2.PdfReader(pdf_file)
    total_pages = len(filereader.pages)
    all_text = ""

    for page_num in range(total_pages):
        page = filereader.pages[page_num]
        all_text += page.extract_text()

    clean_text = all_text.lower()
    clean_text = re.sub(r'\s+', ' ', clean_text)
    clean_text = re.sub(r'[^\x00-\x7F]+', '', clean_text)


    skills = [
        "python", "java", "c++", "sql", "javascript", "apis",
        "machine learning", "deep learning", "nlp", "computer vision",
        "pytorch", "tensorflow", "hugging face", "langchain",
        "data analysis", "data visualization", "excel",
        "react", "node.js", "html", "css"
    ]
    skills_lower = [skill.lower() for skill in skills]

    job_description = """
    We are looking for a Python developer with experience in machine learning, NLP, APIs and SQL.
    Knowledge of PyTorch or TensorFlow is a plus.
    """

    found_skills = [skill for skill in skills_lower if skill in clean_text]
    d_skills = [skill for skill in skills_lower if skill in job_description.lower()]


    common_skills = set(found_skills) & set(d_skills)
    match_score = (len(common_skills) / len(d_skills)) * 100 if d_skills else 0

    missing_skills = set(d_skills) - set(found_skills)
    match_missing_score = (len(missing_skills) / len(d_skills)) * 100 if d_skills else 0


    st.subheader("Skill Analysis")
    st.write(f"Skills found in resume: {', '.join(found_skills)}")
    st.write(f"Skills required in job description: {', '.join(d_skills)}")
    st.write(f"Common skills: {', '.join(common_skills)}")
    st.write(f"Match score: {match_score:.2f}%")
    st.write(f"Missing skills: {', '.join(missing_skills)}")
    st.write(f"Missing score: {match_missing_score:.2f}%")
